= SAÉ 3.01 2022-2023
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/OUF7gxEa).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.

toc::[]

== Equipe

Le projet est réalisé par::

- https://github.com/EnzoMancini[Enzo Mancini]
- https://github.com/EstebanBiret[Esteban Biret-Toscano]
- https://github.com/haisondang[Hai Son Dang]
- https://github.com/Marwwannn[Marwan Youmni]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:laurence.redon@univ-tlse2.fr[LR]

== Contexte général

TIP: Cette partie de votre `README.adoc` peut être supprimée ou mise ailleurs.

=== Dépôt initial

Ce dépôt initial a été créé pour que tous les groupes de 2ème année aient les mêmes informations de départ.

Vous y trouverez des fichiers qui peuvent être supprimés s'ils ne vous sont pas utiles :

- `.gitignore` => un fichier minimaliste des éléments à ne pas pousser en général sur vos dépôts (utiliser la commande `git add -f` pour forcer l'ajout d'un fichier Jar qui ne bougera plus, pour archive par exemple).
- `.github` => le répertoire qui contient des éléments de gestion de projet :
** `workflows` => le repertoire qui contient les actions à lancer à chaque push sur votre repo. 
*** `blank.yml` => un exemple bidon mais dont vous pourrez vérifier l’exécution correcte (1er tag)
** `ISSUE_TEMPLATE` => le repertoire qui contient quelques templates pour vos issues.
*** `us.yml` => Exemple de template pour les User Stories
*** `bug.yml` => Exemple de template pour les issues de bug report

TIP: Adaptez ces fichiers à votre projet et à votre organisation. Et inspirez-vous en pour en ajouter.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

TIP: Pensez à utiliser les salons Discord dédiés pour poser vos questions.

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)

|===========================================================
|Nom du dossier|Lien
| Partie BD (rendus de Webetud dupliqués ici)| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/tree/master/Base%20de%20donn%C3%A9es[ici]
| Partie Web (rendus de Webetud dupliqués ici)| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/tree/master/D%C3%A9veloppement%20Web[ici]
| Partie Communication (rendus de Webetud dupliqués ici)| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/tree/master/Communication[ici]
| Fichiers src du Site-Web| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/tree/master/Fichiers%20src%20site-web[ici]
| Fichiers src IOT| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/tree/master/Fichiers%20src%20IOT[ici]
| Documentation technique WEB à jour| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation/Documentation%20technique%20WEB%20V6.pdf[ici]
| Documentation utilisateur WEB à jour | https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation/Documentation%20utilisateur%20WEB%20V6.pdf[ici]
| Documentation Python|https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/tree/master/Documentation%20Python[ici]
| Tests WEB à jour| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Tests/Test%20Web%20V6.0.adoc[ici]
| Tests Python| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Tests/Test%20Python.py[ici]
| Tests BD V5.0| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Tests/Test%20BD.pdf[ici]
| Analyse d'impact| https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation/Droit%20analyse%20impact.pdf[ici]
| Documentation technique JAVA | https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation%20Java/G1B-6%20Documentation%20technique%20Java.pdf[ici]
|===========================================================

== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/releases/tag/V6.1[V6.1]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation/Backlog%20Produit%20IOT%20%26%20E-commerce.adoc[Backlog produit IOT & E-commerce]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation/Backlog%20Produit%20Sprint%207.adoc[Backlog de Sprint 7]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation/Documentation%20technique%20WEB%20V6.pdf[Documentation technique Web à jour]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/blob/master/Documentation/Documentation%20utilisateur%20WEB%20V6.pdf[Documentation utilisateur Web à jour] 
- https://github.com/orgs/IUT-Blagnac/projects/33[Projet Site Web]
- https://github.com/orgs/IUT-Blagnac/projects/40[Projet IOT]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g1b-6/tree/master/Tests[Tests WEB / IOT / BD] 
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

=== Évaluations hebdomadaires

NOTE: Les notes ci-dessous sont mises à jour directement par les enseignants responsables de la compétence 5.

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1950296416&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1950296416&format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1950296416&format=image"></iframe>
++++
endif::[]

=Sprint 3 retour :
Backlog Ecommerce ok même si des erreurs de syntaxe dans la rédaction. Par contre pourquoi j'ai une colonne US puis Backlog produit ? J'ai encore des "en cours" dans un sprint qui est terminé. Les tâches doivent avoir un label et être assignées. Elles sont aussi ratachées à une US. En IOT pas de backlog produit ni d'organisation en sprint, juste une liste d'issues sans label ni assignement. Des livraisons mais des tests que sur l'IOT. Je n'ai pas touvé vos docs tech et user.




https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1950296416&format=interactive
